# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {Common 17-41} -limit 10000000
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7k70tfbv676-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir H:/project_RISC/project_RISC.cache/wt [current_project]
set_property parent.project_path H:/project_RISC/project_RISC.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo h:/project_RISC/project_RISC.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib C:/Users/AU009TX/Documents/CSN/CSN-221-master/GPRs.v
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}

synth_design -top GPRs -part xc7k70tfbv676-1


write_checkpoint -force -noxdef GPRs.dcp

catch { report_utilization -file GPRs_utilization_synth.rpt -pb GPRs_utilization_synth.pb }
